name: Node CD
on:
  push:
    branches: [master]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: warchant/setup-sonar-scanner@v3
        with:
          node-version: 15
      - run: yarn install
      - run: yarn test:unit
      - run: sonar-scanner
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
