name: Node CD
on:
  push:
    branches: [master]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - run: yarn install
      - run: yarn test:unit
  deploy:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo rm -rf /etc/docker/daemon.json
      - run: echo '{"experimental":false,"insecure-registries":["amrita-elective.tk:5000"]}\n' | sudo tee -a /etc/docker/daemon.json
      - run: sudo systemctl restart docker
      - uses: docker/setup-buildx-action@v1
      - run: docker build -t amrita-elective.tk:5000/api .
      - run: docker push amrita-elective.tk:5000/api
      - uses: fjogeleit/http-request-action@v1.8.0
        id: startContainer
        with:
          url: 'http://amrita-elective.tk:4000/new-api-container'
          method: 'GET'
          timeout: 300000,
      - run: echo ${{ steps.startContainer.outputs.response }}
      - if: ${{ steps.startContainer.outputs.response == '"OK"' }}
        run: exit 0
      - if: ${{ steps.startContainer.outputs.response != '"OK"' }}
        run: exit 1

