name: Node CD
on:
  push:
    branches: [master]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - run: yarn install
      - run: yarn build:prod
      - run: yarn test:unit
  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: amrita-elective.tk:5000/api:latest
      - uses: fjogeleit/http-request-action@v1.8.0
        with:
          id: startContainer
          url: 'http://amrita-elective.tk:4000/new-api-container'
          method: 'GET'
          timeout: 300000,
      - if: ${{ steps.startContainer.outputs.response == 'OK' }}
        run: exit 0
      - if: ${{ steps.startContainer.outputs.response != 'OK' }}
        run: exit 1

