name: Node CD
on:
  push:
    branches: [master]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
            node-version: 15
      - uses: warchant/setup-sonar-scanner@v3
      - run: yarn install
      - run: yarn test:unit
      - run: sonar-scanner
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  deploy:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: sudo rm -rf /etc/docker/daemon.json
      - run: echo '{"experimental":false,"insecure-registries":["amrita-elective.tk:5000"]}\n' | sudo tee -a /etc/docker/daemon.json
      - run: sudo systemctl restart docker
      - uses: docker/login-action@v1
        with:
          registry: amrita-elective.tk:5000
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - run: docker build -t amrita-elective.tk:5000/api .
      - run: docker push amrita-elective.tk:5000/api
      - uses: Satak/webrequest-action@v1.2.3
        id: startContainer
        with:
          url: https://amrita-elective.tk:4000/new-api-container
          method: POST
          payload: ${{ secrets.EC2_LOGIN }}
      - run: echo ${{ steps.startContainer.outputs.output }}
      - if: ${{ steps.startContainer.outputs.response.data == 'OK' }}
        run: exit 0
      - if: ${{ steps.startContainer.outputs.response.data != 'OK' }}
        run: exit 1
