name: Node CD
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
            registry: 'http://amrita-elective.tk:5000'
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: amrita-elective.tk:5000/api:latest
      - uses: fjogeleit/http-request-action@v1.8.0
        with:
          id: startContainer
          url: 'http://amrita-elective.tk:4000/new-api-container'
          method: 'GET'
          timeout: 300000,
      - if: ${{ steps.startContainer.outputs.response == 'OK' }}
        run: exit 0
      - if: ${{ steps.startContainer.outputs.response != 'OK' }}
        run: exit 1

