name: Node CD
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
        echo '{"experimental": true,\n' | sudo tee -a /etc/docker/daemon.json
      - run: echo '"insecure-registries":["amrita-elective.tk:5000"]}\n' | sudo tee -a /etc/docker/daemon.json
      - uses: docker/setup-buildx-action@v1
      - run: docker build -t amrita-elective.tk:5000/api .
      - run: docker push amrita-elective.tk:5000/api
      - uses: fjogeleit/http-request-action@v1.8.0
        with:
          id: startContainer
          url: 'http://amrita-elective.tk:4000/new-api-container'
          method: 'GET'
          timeout: 300000,
      - if: ${{ steps.startContainer.outputs.response == 'OK' }}
        run: exit 0
      - if: ${{ steps.startContainer.outputs.response != 'OK' }}
        run: exit 1

