name: Node CI
on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Setup cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn install
      - name: suggest & lint
        uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
      - name: prettier
        run: yarn prettier
      - name: Build API
        run: yarn build:prod
      - name: Run tests
        run: yarn test:unit
      - name: set time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Discord notification success
        if: success()
        uses: hugoalh/GitHubAction.SendToDiscord@v3.0.0
        with:
          configuration: ".github/workflows_configuration/integration-success.json"
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{secrets.DISCORD_WEBHOOK_TOKEN}}
          variable_join: "."
          variable_prefix: "%"
          variable_suffix: "%"
      - name: Discord notification failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"Integration failed","color":12845619,"fields":[{"name":"Triggered by:","value":"${{ github.actor }}"},{"name":"Event: pull request","value":"[${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }})"},{"name":"Workflow","value":"[${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}],"timestamp":"${{ steps.current-time.outputs.time }}"}]'
        uses: Ilshidur/action-discord@master
