name: Node CI
on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      embed_string_success: '[{"title":"CI successful","color":43878,"fields":[{"name":"Trigger by:","value":"${{ github.actor }}"},{"name":"Event: ${{ github.event_name }}","value":"[${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/${{ github.event_name }}/${{ github.ref }})"},{"name":"Action","value":"[${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}]}]'
      embed_string_failure: '[{"title":"CI failed","color":12845619,"fields":[{"name":"Trigger by:","value":"${{ github.actor }}"},{"name":"Event: ${{ github.event_name }}","value":"[${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/${{ github.event_name }}/${{ github.ref }})"},{"name":"Action","value":"[${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}]}]'
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Setup cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint:fix
      - name: Build API
        run: yarn build:prod
      - name: Run tests
        run: yarn test:unit
      - name: Discord notification success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ env.embed_string_success }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} merge request tests completed!'
      - name: Discord notification failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ env.embed_string_failure }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} merge request tests completed!'
