name: Notfiy
on:
  push:
    branches-ignore:
      - master

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify commit
        uses: nebularg/actions-discord-webhook@v1.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

